name: icon
sdf: False
training:
  data_name: 'thuman'
  gpus: [3]
  test_gpus: [3]
  thresh: 0.5
net:
  use_filter: False
  geometric_init: False
  geo_feat_dict: {'projected': ['nndist']}
  point_feat_dim: 1
  loss_type: ['occ']

# user defined
mcube_res: 256    # occupancy field resolution, higher --> more details
clean_mesh: True # if True, will remove floating pieces