name: Ours
sdf: True
training:
  gpus: [1]
  test_gpus: [1]
  thresh: 0.
net:
  geometric_init: True
  geo_feat_dict: {'canon': ['nndist', 'points']}
  point_feat_dim: 4
  lambda_igr_surf_sdf: 1.
  lambda_igr_off_sdf: 1.
  lambda_nml: 1.0
  lambda_grad: 0.1
  loss_type: ['igr_sdf', 'normal', 'gradient']

# user defined
mcube_res: 256    # occupancy field resolution, higher --> more details
clean_mesh: True # if True, will remove floating pieces