name: pifu
sdf: False
training:
  data_name: 'thuman'
  gpus: [3]
  test_gpus: [3]
  thresh: 0.5
  freq_show_train: 0.03
  freq_show_val: 0.03
  freq_eval: 0.1
  freq_save: 0.01
net:
  geometric_init: False
  geo_feat_dict: {'projected': ['depth']}
  point_feat_dim: 1
  loss_type: ['occ']

# user defined
mcube_res: 256    # occupancy field resolution, higher --> more details
clean_mesh: True # if True, will remove floating pieces